# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{em-synchrony}
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Grigorik"]
  s.date = %q{2010-06-19}
  s.description = %q{Fiber aware EventMachine libraries}
  s.email = %q{ilya@igvita.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "examples/all.rb",
     "examples/bitly.rb",
     "lib/em-synchrony.rb",
     "lib/em-synchrony/connection_pool.rb",
     "lib/em-synchrony/em-bitly.rb",
     "lib/em-synchrony/em-http.rb",
     "lib/em-synchrony/em-jack.rb",
     "lib/em-synchrony/em-mongo.rb",
     "lib/em-synchrony/em-multi.rb",
     "lib/em-synchrony/em-mysqlplus.rb",
     "lib/em-synchrony/em-remcached.rb",
     "lib/em-synchrony/iterator.rb",
     "spec/beanstalk_spec.rb",
     "spec/connection_pool_spec.rb",
     "spec/helper/all.rb",
     "spec/helper/stub-http-server.rb",
     "spec/helper/tolerance_matcher.rb",
     "spec/http_spec.rb",
     "spec/iterator_spec.rb",
     "spec/mongo_spec.rb",
     "spec/mysqlplus_spec.rb",
     "spec/remcached_spec.rb"
  ]
  s.homepage = %q{http://github.com/igrigorik/em-synchrony}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9")
  s.rubyforge_project = %q{em-synchrony}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Fiber aware EventMachine libraries}
  s.test_files = [
    "spec/beanstalk_spec.rb",
     "spec/connection_pool_spec.rb",
     "spec/helper/all.rb",
     "spec/helper/stub-http-server.rb",
     "spec/helper/tolerance_matcher.rb",
     "spec/http_spec.rb",
     "spec/iterator_spec.rb",
     "spec/mongo_spec.rb",
     "spec/mysqlplus_spec.rb",
     "spec/remcached_spec.rb",
     "examples/all.rb",
     "examples/bitly.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.9"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0.12.9"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0.12.9"])
  end
end

